### PR TITLE
Feature/custom ssh port (updated)

### PR DESCRIPTION
**Pull request by wzulfikar**
- Renamed `$PORT` $port`
- removed `@$connectionParameters['port'] ?: 22;` because the port is already defined in config file

### CODE REVIEW

**Comment by freekmurze** [comment]
Have you tested this out?

What happens if the port is not defined in the config file?

**Comment by wzulfikar** [comment]
1. Yes, i tested it using default port, 22 and custom port 8888 
artisan-tail-production-22
artisan-tail-production-8888
2. It will throw undefined index, same behaviour as when `user` key is not defined
artisan-tail-undefined-user-or-port

**Comment by freekmurze** [comment]
Could you please make your change backwards compatible? I don't want this package to break when `port` is not defined in the config file. Avoid using `@` to suppress errors.

**Comment by wzulfikar** [comment]
updated. port defaults to 22 if it's not defined in config file.

**Comment by freekmurze** [comment]
Thanks, I'll hack a bit on this myself an tag a release.

**Comment by wzulfikar** [comment]
Thanks!

**Pull request merged**
