### PR TITLE
Add '--hide-stack-traces' option

### PR DESCRIPTION
**Pull request by aryehraber**
Took a crack at adding this option, as per Freek's tweet: 
https://twitter.com/freekmurze/status/1031241488427114496

Let me know if you'd like to see any changes!

### CODE REVIEW

**Comment by jszobody** [comment]
I've never seen the need for this package in the past when I can so easily tail my own log file. This PR will likely change my mind, looks super helpful!

Might I suggest adding a shortcut to this option? Maybe `-H` or whatever you feel most appropriate. It's pretty long to type out.

**Comment by mattdfloyd** [comment]
It doesn't appear that the `--color` flag on the grep command is working since the actual output is being piped through a Symfony component. Color and Style could possibly be handled by Symfony, or the expectation could be dropped entirely by removing the flag.

**Comment by aryehraber** [comment]
Thanks @mattdfloyd, seems I missed that little bug. 

Took a (quick) dive into the Symfony Process component, and it seems adding the `setTty(true)` method fixes the issue (as per https://github.com/symfony/symfony-docs/issues/6188).

**Comment by freekmurze** [comment]
Thank you very much for this @aryehraber 👍

**Comment by freekmurze** [comment]
@aryehraber on my machine (running the latest MacOS). The `-H` option doesn't work. Running `php artisan -H` displays the last lines of the log, but if lines are appended to the log, it doesn't show in the console output.

Also, running `php artisan -H` should initially displaying nothing. Could you send a PR that fixes this?

**Comment by aryehraber** [comment]
@freekmurze Taking another look -- everything seemed fine when I last checked.

**Comment by freekmurze** [comment]
Thanks for taking another look. This is what I'm seeing at my end: https://www.dropbox.com/s/kpj61ic52czo462/tail.mov?dl=0

**Comment by freekmurze** [comment]
No worries if you don't find a solution, then I'll just revert the PR and take a detailed look myself in the coming days / weeks

**Comment by aryehraber** [comment]
@freekmurze Thanks for the vid, I'm also seeing issues on my side — apologies!

If I'm able to resolve it I'll push to this PR, will let you know otherwise so you can revert!

**Comment by freekmurze** [comment]
I don't know if you can push to an already merged PR. If this gives you troubles, just open up a new PR.

**Comment by aryehraber** [comment]
@freekmurze haha good point 😅 I'll submit a new PR!

Btw, I think I've found the solution, though there's a slight limitation; it doesn't seem (easily) possible to use `--lines` + `-H` at the same time because the lines are "selected" from the log file _before_ the filter does its thing, so the behaviour isn't quite what you'd expect. Individually they now work though, so I'll push this up soon!

**Pull request merged**
